#!/bin/bash

# Add gitlab to hosts file
grep -q -F "$GIT_HOSTS" /etc/hosts  || echo $GIT_HOSTS >> /etc/hosts

# Clone repo to container
git clone -b $GIT_BRANCH $GIT_REPO /usr/share/nginx/html/

# Copy in post-merge script to run npm install
cat /post-merge >> /usr/share/nginx/html/.git/hooks/post-merge
chmod +x /usr/share/nginx/html/.git/hooks/post-merge

# run node prep commands
cd /usr/share/nginx/html/ && eval ${NODE_PREP}

#start cron in the background
/usr/sbin/cron -f &

# Start Apache server
nginx -g "daemon off;"

